"use client"
import { useRef } from "react"
import { motion, useInView, useScroll, useTransform, type MotionValue } from "framer-motion"
import { DepthCard, Reveal, usePortfolioMotion } from "@/components/motion-system"
import { SectionHeading } from "@/components/section-heading"
function Word({ word, progress, start, end }: {word:string;progress:MotionValue<number>;start:number;end:number}) { const opacity=useTransform(progress,[start,end],[.36,1]);const {enabled}=usePortfolioMotion();return <motion.span style={{opacity:enabled?opacity:1}}>{word} </motion.span> }
function ScrollWords({text}:{text:string}) { const ref=useRef<HTMLParagraphElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start .9','end .5']});const words=text.split(' ');return <p ref={ref} className="scroll-words">{words.map((word,i)=><Word key={i} word={word} progress={scrollYProgress} start={i/words.length} end={(i+1)/words.length}/>)}</p> }
function PortraitPhoto() {
 const ref=useRef<HTMLDivElement>(null), visible=useInView(ref,{once:true,amount:.25})
 const {enabled}=usePortfolioMotion()
 return <motion.div ref={ref} className="portrait-image" initial={false} animate={{clipPath:!enabled||visible?'inset(0% 0% 0% 0% round 9px)':'inset(8% 0% 8% 0% round 9px)'}} transition={{duration:enabled?.9:0,ease:[.22,1,.36,1]}}><img src="/profile.jpg" width={619} height={791} alt="B Pranavkrishna Vadhyar speaking at an event" loading="lazy"/></motion.div>
}
export function AboutSection(){return <section id="about" className="section-shell about-section"><SectionHeading index="01" label="THE PERSON BEHIND THE PIPELINE" title={<>Curiosity in.<br/><span className="text-gradient">Real-world impact out.</span></>}/><div className="about-layout"><Reveal className="about-portrait"><DepthCard className="portrait-card"><div className="portrait-orbit" aria-hidden="true"/><PortraitPhoto/><div className="portrait-caption"><span className="status-light"/><span>ENGINEER. RESEARCHER. EDUCATOR. BUILDER.</span></div><span className="portrait-corner" aria-hidden="true">PV / 01</span></DepthCard></Reveal><Reveal className="about-copy"><ScrollWords text="I build intelligent systems at the intersection of generative AI and backend engineering. From language models and RAG pipelines to agents and inference systems, I turn research into applications that work in the real world."/><p>Experienced with TensorFlow, FastAPI, PostgreSQL, LangChain, and CrewAI, I connect AI research with deployment. Beyond the code, I mentor, lead workshops, and build communities around practical AI.</p><div className="about-flow" aria-label="Research to architecture to deployment"><span>Research</span><i/><span>Architecture</span><i/><span>Deployment</span></div><div className="about-note"><span>BASED IN</span><strong>Kochi, Kerala</strong><span>THINKING IN</span><strong>Systems &amp; possibilities</strong></div></Reveal></div><div className="section-dust" aria-hidden="true"/></section>}
