"use client"
import { useState } from "react"
import { Award, Users, Star, Trophy, ArrowUpRight, RotateCcw } from "lucide-react"
import { Counter, Reveal } from "@/components/motion-system"
import { SectionHeading } from "@/components/section-heading"
const awards=[
 {title:'Best Outgoing Student',icon:Award,year:'2025',type:'Recognition',description:'Best outgoing student of the Department of Computer Science for 2021–25.',organization:'Toc H Institute of Science and Technology'},
 {title:'Founder of Core.ai',icon:Users,year:'2024',type:'Community',description:'Launched and led Core.ai, the official AI club of Toc H.',organization:'Core.ai'},
 {title:'Training & Mentoring',icon:Star,year:'2023 – Present',type:'Impact',description:'Trained 500+ students across Kerala colleges in technical topics.',organization:'Colleges across Kerala'},
 {title:'Spark Venture 2024',icon:Trophy,year:'2024',type:'Innovation',description:'Secured second place and Rs 75,000 funding for FirstaidPro.',organization:'Freston Analytics'},
]
export function AchievementsSection(){const [flipped,setFlipped]=useState<number|null>(null);return <section id="achievements" className="section-shell achievements-section"><div className="achievements-intro"><SectionHeading index="05" label="IMPACT BEYOND THE CODE" title={<>Build. Share.<br/><span className="text-gradient">Move people forward.</span></>}/><div className="medal-scene" aria-hidden="true"><div className="medal-orbit"/><div className="medal-object"><div className="medal-face"><Trophy size={55} strokeWidth={1}/></div><div className="medal-edge"/><div className="medal-ribbon ribbon-a"/><div className="medal-ribbon ribbon-b"/></div></div></div><div className="impact-metrics"><div><strong><Counter value={500} suffix="+"/></strong><span>STUDENTS MENTORED</span></div><div><strong><Counter value={75000} prefix="₹"/></strong><span>PROJECT FUNDING</span></div><div><strong>01</strong><span>AI COMMUNITY FOUNDED</span></div></div><div className="award-grid">{awards.map((award,i)=>{const Icon=award.icon;return <Reveal key={award.title} delay={i*.06}><article onPointerEnter={e=>{if(e.pointerType==="mouse")setFlipped(i)}} onPointerLeave={e=>{if(e.pointerType==="mouse"&&!e.currentTarget.contains(document.activeElement))setFlipped(null)}} className={`award-card ${flipped===i?'is-flipped':''}`}><div className="award-flipper"><div className="award-front" aria-hidden={flipped===i}><div className="award-meta"><Icon size={23}/><span>{award.year}</span></div><span className="mono-label">{award.type}</span><h3>{award.title}</h3><p>{award.organization}</p></div><div className="award-back" aria-hidden={flipped!==i}><span className="mono-label">{award.year} / {award.type}</span><h3>{award.title}</h3><p>{award.description}</p></div></div><button className="award-toggle" onClick={()=>setFlipped(flipped===i?null:i)} aria-expanded={flipped===i} aria-label={`${flipped===i?"Back from":"Details about"} ${award.title}`}>{flipped===i?<><RotateCcw size={14}/> Back</>:<>View impact <ArrowUpRight size={15}/></>}</button></article></Reveal>})}</div></section>}
